<h3>Novo Registro</h3>
<div class="pull-right">
	<a
		href="<?php echo $this->url('estudante', array('controller' => 'estudante')); ?>"
		class="btn btn-primary">Voltar</a> <br /> <br />
</div>

<?php 
// 	$this->form->prepare();
// 	$this->form->setAttribute('action', $this->url('estudante',array('action'=>'add')));
	
// 	echo $this->form()->openTag($this->form);
// 	echo $this->formHidden($this->form->get('matricula'));
// 	echo $this->formRow($this->form->get('nome'));
// 	echo $this->formSubmit($this->form->get('submit'));
// 	echo $this->form()->closeTag();

?>

